- hosts: docker
  tasks:
     - name: install python
       yum:
         name: python-docker
         state: present
     - name: running container
       docker_container:
         image: ajizkai/boilerplate
         state: started
         interactive: yes
         tty: yes
         detach: yes
exposed_port: 8080
